Securiryfix: Removed all use of USB as an alternative to CDROM. Added GPL text.

diff --git a/modules/puppet_tripwire/files/tripwire.init b/modules/puppet_tripwire/files/tripwire.init
--- a/modules/puppet_tripwire/files/tripwire.init
+++ b/modules/puppet_tripwire/files/tripwire.init
@@ -7,15 +7,29 @@
 ##############################################################
 ## Console usage: tripwire.init
 ## Initilize our database with tripwire binary
-## and the site/host key files on CDROM or USB.
+## and the site/host key files on CDROM.
+#
+# Copyright (C) (2012) K-B.Kronlund <bkronmailbox-copyright@yahoo.se>
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
 
 MOUNT="/bin/mount"
 UMOUNT="/bin/umount"
 
 MNTPOINT="/media/tripwire"
-
 CDDEV="/dev/sr0"
-USBDEV="/dev/sdb1"
 
 TWDBPATH="/var/lib/tripwire"
 HOSTNAME=`uname -n`
@@ -30,34 +44,17 @@ if [ ! -e $TWDBPATH/${HOSTNAME}.twd ] ; then
 	echo "Tripwire database for ${HOSTNAME} is not found. Initilizing a new database."
 fi
 
-# Ensure that non of the devices is mounted
-# since CDROM/USB are mounted on the same MNTPOINT
-
-$UMOUNT $CDDEV > /dev/null 2>&1
-$UMOUNT $USBDEV > /dev/null 2>&1
 
 ## If grep does not return 0, mount the CDROM
 
 cat /etc/mtab | grep sr0
 if [ $? -ne 0 ] ; then
-	$MOUNT $CDDEV $MNTPOINT > /dev/null 2>&1
-fi
-
-# If the CDROM mount failed ($?) try an USB mount
-
-if [ $? -ne 0 ] ; then  
-
-    cat /etc/mtab | grep sdb1
-    if [ $? -ne 0 ] ; then
-    	$MOUNT $USBDEV $MNTPOINT > /dev/null 2>&1
+	$MOUNT $CDDEV $MNTPOINT
+    # If mount attempts failed, abort
+    if [ $? -ne 0 ] ; then  
+        echo "$0: Error: Can't mount tripwire media! No CD disk found or error reading it."
+        exit 1
     fi
-    
-fi
-
-# If both mount attempts failed, abort
-if [ $? -ne 0 ] ; then  
-    echo "$0: Error: Can't mount tripwire media! No CD disk or USB stick found."
-    exit 1
 fi
 
 ## Set new file mask
